import = ["~/.config/alacritty/catppuccin-frappe.toml"]

live_config_reload = true

[window]
decorations = "buttonless"
option_as_alt = "Both"
blur = true
opacity = 0.85
padding = { x = 10, y = 10 }

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 13

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "M", mods = "Command", action = "ToggleFullscreen" },
]
