# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't insert a blank line between shell prompts
add_newline = false

right_format = "$kubernetes"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "cyan bold"

[docker_context]
disabled = true

[golang]
format = "via [$symbol($version )]($style)"

[git_status]
format = '([\[$ahead_behind\]]($style) )'

[kubernetes]
disabled = false
format = ' in [$symbol$context( \($namespace\))]($style) '

[username]
disabled = true
